on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: 'Publish package to PyPI'
    environment: 'PyPI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'poetry'
      - run: poetry install
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: make publish
